export const items =  [
    {
      id: 1,
      category: 'mobiles',
      title: "Apple iPhone 14",
      imgSrc: 'https://m.media-amazon.com/images/I/61bK6PMOC3L._SX679_.jpg',
      amazonLink: 'https://amzn.to/3PuckZp',
      description: 'Apple iPhone 14 (128 GB) - Blue',
      price: '89999',
    },
    {
      id: 5,
      category: 'laptops',
      title: "Xiaomi [Smartchoice] Notebookpro",
      imgSrc: 'https://m.media-amazon.com/images/I/71iiXU7HHkL._SY450_.jpg',
      amazonLink: 'https://amzn.to/3EzeQaC',
      description: 'Xiaomi [Smartchoice] Notebookpro ',
      price: '49999',
    },
    {
      id: 7,
      category: 'tablets',
      title: "Xiaomi Pad 6",
      imgSrc: 'https://m.media-amazon.com/images/I/71LRY1j6UHL._SX679_.jpg',
      amazonLink: 'https://amzn.to/3ZeNRdY',
      description: 'Xiaomi Pad 6| Qualcomm Snapdragon 870| ',
      price: '29999',
    },
    {
      id: 2,
      category: 'mobiles',
      title: "Apple iPhone 11",
      imgSrc: 'https://m.media-amazon.com/images/I/71QE00iB9IL._SX679_.jpg',
      amazonLink: 'https://amzn.to/44MiYi6',
      description: 'Apple iPhone 11 (64GB) - White',
      price: '39999',
    },
    {
      id: 6,
      category: 'tablets',
      title: "Lenovo Tab P12 Pro AMOLED",
      imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg',
      amazonLink: 'https://amzn.to/3RabsdH',
      description: 'Lenovo Tab P12 Pro AMOLED (12.6 inch (32 cm), 8 GB, 256 GB, Wi-fi Only), Storm Grey with Precision Pen 3',
      price: '19999',
    },
    {
      id: 3,
      category: 'mobiles',
      title: "Apple iPhone 13",
      imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SX679_.jpg',
      amazonLink: 'https://amzn.to/3r6XJtv',
      description: 'Apple iPhone 13 (128GB) - Blue',
      price: '69999',
    },
    {
      id: 4,
      category: 'laptops',
      title: "Lenovo IdeaPad Slim 5 ",
      imgSrc: 'https://m.media-amazon.com/images/I/81d4ZCaBnsL._SX679_.jpg',
      amazonLink: 'https://amzn.to/44JsK4r',
      description: 'Lenovo IdeaPad Slim 5 Intel Core i5 12450H 14" (35.5cm) ',
      price: '29999',
    },
    {
      id: 9,
      category: 'tablets',
      title: "Samsung Galaxy Tab A8",
      imgSrc: 'https://m.media-amazon.com/images/I/91veRYPjpeL._SX679_.jpg',
      amazonLink: 'https://amzn.to/3Pdsh4F',
      description: 'Samsung Galaxy Tab A8 26.69cm (10.5 inch) Display, RAM 4 GB, ROM 64 GB Expandable, Wi-Fi Tablet, Gray, (SM-X200NZAEINU)',
      price: '49999',
    },
    {
      id: 8,
      category: 'laptops',
      title: "Apple MacBook Air Laptop",
      imgSrc: 'https://m.media-amazon.com/images/I/71jG+e7roXL._SX679_.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'Apple MacBook Air Laptop M1 chip, 13.3-inch/33.74 cm Retina Display, ',
      price: '89999',
    },
    {
        id: 9,
        category: 'tablets',
        title: "Redmi Pad SE",
        imgSrc: 'https://m.media-amazon.com/images/I/710WMfH99HL._SY450_.jpg',
        amazonLink: 'https://amzn.in/d/96938W8',
        description: 'Redmi Pad SE| All Day Battery | Qualcomm Snapdragon 680| 90Hz Refresh Rate| 4GB, 128GB Tablet| FHD+ Display (11-inch/27.81cm)| Dolby Atmos| Quad Speakers| Wi-Fi| Gray ',
        price: '12999',
      },
      {
        id: 10,
        category: 'tablets',
        title: "Lenovo Tab M11",
        imgSrc: 'https://m.media-amazon.com/images/I/51WLV2ZemjL._SY450_.jpg',
        amazonLink: 'https://amzn.in/d/3ReEoYP',
        description: 'Lenovo Tab M11 with Pen| Wi-Fi Connectivity| 8 GB RAM, 128 GB ROM|11 Inch Screen| 90 Hz, 72% NTSC, FHD Display| Quad Speakers with Dolby Atmos|Octa-Core Processor |13 MP Rear Camera, ',
        price: '16999',
      },
      {
        id: 11,
        category: 'tablets',
        title: "OnePlus Pad Go",
        imgSrc: 'https://m.media-amazon.com/images/I/51oj5gE7P+L._SY355_.jpg',
        amazonLink: 'https://amzn.in/d/3FVKDrs',
        description: 'OnePlus Pad Go 28.85cm (11.35 inch) 2.4K 7:5 ratio ReadFit Eye Care LCD Display, Dolby Atmos Quad Speakers,Wi-Fi Only, 8GB RAM 128 GB ROM Expandable Up-to 1TB, Twin Mint Colour, ',
        price: '18999',
      },
      {
        id: 12,
        category: 'tablets',
        title: "Samsung Galaxy Tab S9 FE+",
        imgSrc: 'https://m.media-amazon.com/images/I/61l5a94VKkL._SX450_.jpg',
        amazonLink: 'https://amzn.in/d/j6Q7wkp',
        description: 'Samsung Galaxy Tab S9 FE+ 31.50 cm (12.4 inch) Display, RAM 8 GB, ROM 128 GB Expandable, S Pen in-Box, Wi-Fi, IP68 Tablet, Gray, ',
        price: '33490',
      },
      {
        id: 13,
        category: 'tablets',
        title: "Samsung Galaxy Tab S9 Ultra",
        imgSrc: 'https://m.media-amazon.com/images/I/71LviO0dvIL._SY450_.jpg',
        amazonLink: 'https://amzn.in/d/0fUqVGB',
        description: 'Samsung Galaxy Tab S9 Ultra 36.99 cm (14.6 inch) Dynamic AMOLED 2X Display, RAM 12 GB, ROM 512 GB Expandable, S Pen in-Box, Wi-Fi Tablet, Gray, ',
        price: '108999',
      },
      {
        id: 14,
        category: 'laptops',
        title: "Samsung Galaxy Book4 Pro ",
        imgSrc: 'https://m.media-amazon.com/images/I/31oHC+Z+RuL._SX450_.jpg',
        amazonLink: 'https://amzn.in/d/3Iylobr',
        description: 'Samsung Galaxy Book4 Pro | Intel Evo Core Ultra 5 125H | Built-in AI | 16" (40.64cm) Touchscreen Dynamic AMOLED 2X 120Hz| 500 Nits (16GB/512GB SSD/Intel Arc/Win11/MSO, ',
        price: '133990',
      },
      {
        id: 15,
        category: 'laptops',
        title: "Lenovo Yoga Slim",
        imgSrc: 'https://m.media-amazon.com/images/I/81XI2oO6y1L._SX450_.jpg',
        amazonLink: 'https://amzn.in/d/bHT2IhM',
        description: 'Lenovo Yoga Slim 7 Intel Core Ultra 7 155H Built-in AI 14"(35.5cm) WUXGA-OLED 400Nits Laptop (32GB/1TB SSD/100% DCI-P3/FHD+IR Camera/Win11, ',
        price: '105799',
      },
      {
        id: 16,
        category: 'laptops',
        title: "Apple 2023 MacBook Pro",
        imgSrc: 'https://m.media-amazon.com/images/I/618d5bS2lUL._SX522_.jpg',
        amazonLink: 'https://amzn.in/d/fkqtcEl',
        description: 'Apple 2023 MacBook Pro (16-inch, M3 Pro chip with 12‑core CPU and 18‑core GPU, 18GB Unified Memory, 512GB) , ',
        price: '229990',
      },
      {
        id: 17,
        category: 'mobiles',
        title: "Apple iPhone 15 ",
        imgSrc: 'https://m.media-amazon.com/images/I/71657TiFeHL._SX522_.jpg',
        amazonLink: 'https://amzn.in/d/0wGOBPR',
        description: 'Apple iPhone 15 (512 GB) - Black, ',
        price: '95699',
      },
      {
        id: 18,
        category: 'mobiles',
        title: "Apple iPhone 15 Pro",
        imgSrc: 'https://m.media-amazon.com/images/I/81CgtwSII3L._SX522_.jpg',
        amazonLink: 'https://amzn.in/d/7j6S61O',
        description: 'Apple iPhone 15 Pro (1 TB) - Natural Titanium, ',
        price: '189999',
      },
      {
        id: 19,
        category: 'mobiles',
        title: "Apple iPhone 15 Plus",
        imgSrc: 'https://m.media-amazon.com/images/I/71bErtQPC3L._SX522_.jpg',
        amazonLink: 'https://amzn.in/d/ejoCiAQ',
        description: 'Apple iPhone 15 Plus (256 GB) - Pink, ',
        price: '99999',
      },
      {
        id: 20,
        category: 'mobiles',
        title: "Samsung Galaxy S24 Ultra 5G",
        imgSrc: 'https://m.media-amazon.com/images/I/81vxWpPpgNL._SX569_.jpg',
        amazonLink: 'https://amzn.in/d/cHKNB8z',
        description: 'Samsung Galaxy S24 Ultra 5G AI Smartphone (Titanium Gray, 12GB, 256GB Storage), ',
        price: '129999',
      },
      {
        id: 21,
        category: 'mobiles',
        title: "Samsung Galaxy S24 5G",
        imgSrc: 'https://m.media-amazon.com/images/I/71r4P+34FuL._SX569_.jpg',
        amazonLink: 'https://amzn.in/d/ey9RUi6',
        description: 'Samsung Galaxy S24 5G AI Smartphone (Onyx Black, 8GB, 256GB Storage), ',
        price: '64999',
      },
      {
        id: 22,
        category: 'mobiles',
        title: "OnePlus Nord CE4 Lite 5G",
        imgSrc: 'https://m.media-amazon.com/images/I/51KJE22BKrL._SX569_.jpg',
        amazonLink: 'https://amzn.in/d/cjfFTm8',
        description: 'OnePlus Nord CE4 Lite 5G (Ultra Orange, 8GB RAM, 128GB Storage), ',
        price: '19999',
      },
      {
        id: 23,
        category: 'laptops',
        title: "Apple MacBook Air Laptop",
        imgSrc: 'https://m.media-amazon.com/images/I/71jG+e7roXL._SX679_.jpg',
        amazonLink: 'https://amzn.to/3r9rvhm',
        description: 'Apple MacBook Air Laptop M1 chip, 13.3-inch/33.74 cm Retina Display, ',
        price: '89999',
      },
      {
        id: 24,
        category: 'laptops',
        title: "Apple MacBook Air Laptop",
        imgSrc: 'https://m.media-amazon.com/images/I/71jG+e7roXL._SX679_.jpg',
        amazonLink: 'https://amzn.to/3r9rvhm',
        description: 'Apple MacBook Air Laptop M1 chip, 13.3-inch/33.74 cm Retina Display, ',
        price: '89999',
      },
      {
        id: 25,
        category: 'laptops',
        title: "Apple MacBook Air Laptop",
        imgSrc: 'https://m.media-amazon.com/images/I/71jG+e7roXL._SX679_.jpg',
        amazonLink: 'https://amzn.to/3r9rvhm',
        description: 'Apple MacBook Air Laptop M1 chip, 13.3-inch/33.74 cm Retina Display, ',
        price: '89999',
      },
      {
        id: 26,
        category: 'laptops',
        title: "Apple MacBook Air Laptop",
        imgSrc: 'https://m.media-amazon.com/images/I/71jG+e7roXL._SX679_.jpg',
        amazonLink: 'https://amzn.to/3r9rvhm',
        description: 'Apple MacBook Air Laptop M1 chip, 13.3-inch/33.74 cm Retina Display, ',
        price: '89999',
      },
      {
        id: 27,
        category: 'laptops',
        title: "Apple MacBook Air Laptop",
        imgSrc: 'https://m.media-amazon.com/images/I/71jG+e7roXL._SX679_.jpg',
        amazonLink: 'https://amzn.to/3r9rvhm',
        description: 'Apple MacBook Air Laptop M1 chip, 13.3-inch/33.74 cm Retina Display, ',
        price: '89999',
      },
      {
        id: 28,
        category: 'laptops',
        title: "Apple MacBook Air Laptop",
        imgSrc: 'https://m.media-amazon.com/images/I/71jG+e7roXL._SX679_.jpg',
        amazonLink: 'https://amzn.to/3r9rvhm',
        description: 'Apple MacBook Air Laptop M1 chip, 13.3-inch/33.74 cm Retina Display, ',
        price: '89999',
      },
      {
        id: 29,
        category: 'laptops',
        title: "Apple MacBook Air Laptop",
        imgSrc: 'https://m.media-amazon.com/images/I/71jG+e7roXL._SX679_.jpg',
        amazonLink: 'https://amzn.to/3r9rvhm',
        description: 'Apple MacBook Air Laptop M1 chip, 13.3-inch/33.74 cm Retina Display, ',
        price: '89999',
      },{
        id: 30,
        category: 'laptops',
        title: "Apple MacBook Air Laptop",
        imgSrc: 'https://m.media-amazon.com/images/I/71jG+e7roXL._SX679_.jpg',
        amazonLink: 'https://amzn.to/3r9rvhm',
        description: 'Apple MacBook Air Laptop M1 chip, 13.3-inch/33.74 cm Retina Display, ',
        price: '89999',
      },


  ]